Update MessageException usage
MessageException was updated in openseedbox/openseedbox-common@f84c92d2b87161828f84a670011a062adcabfdf1
and now it doesn't compile.

play.exceptions.CompilationException: The constructor MessageException(IOException, String) is undefined
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:264)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:300)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:420)
	at play.Play.preCompile(Play.java:609)
	at play.Play.init(Play.java:309)
	at play.server.Server.main(Server.java:160)